; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = client

[env:client]
platform = espressif32
board = esp32dev
framework = arduino
lib_deps = sandeepmistry/LoRa@^0.8.0
	adafruit/Adafruit Unified Sensor@^1.1.15
	adafruit/DHT sensor library@^1.4.6
	PaulStoffregen/OneWire@^2.3.5
	milesburton/DallasTemperature@^3.9.1
lib_extra_dirs = lib
build_flags = -D SENSOR_PIN=2 -D PH_SENSOR_PIN=19 -D DEVICE_ID="client-01" -D LORA_FREQUENCY=915000000 -D ADXL345_SDA_PIN=16 -D ADXL345_SCL_PIN=17 -D BH1750_SDA_PIN=16 -D BH1750_SCL_PIN=17 -D TEMP_SENSOR_PIN=4 -D TEMP_SENSOR_TYPE=DHT22 -I lib/shared/include -DUSE_SODIUM -DPRIVATE_KEY_B64=\"<BASE64_PRIVATE_KEY>\"
build_src_flags = -I lib/shared/include
